import type { Product } from "../types";

 export const products: Product[] = [
  {
    id: '1',
    name: 'Velvet Dusk Evening Gown',
    price: 129.99,
    originalPrice: 219.99,
    discountPercentage: 40,
    description: 'A stunning deep violet floor-length gown with premium velvet finish and elegant slit.',
    category: 'Occasion',
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680fe0a?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: '2',
    name: 'Lavender Oversized Hoodie',
    price: 45.00,
    description: 'Ultra-soft fleece oversized hoodie in a calming lavender shade. Perfect for cozy street style.',
    category: 'Streetwear',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: '3',
    name: 'Urban Violet Sneakers',
    price: 89.00,
    originalPrice: 149.00,
    discountPercentage: 40,
    description: 'High-performance athletic sneakers with unique violet accents and air-cushion technology.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: '4',
    name: 'Amethyst Crystal Pendant',
    price: 32.00,
    originalPrice: 45.00,
    discountPercentage: 28,
    description: 'Handcrafted sterling silver necklace featuring a raw amethyst crystal point.',
    category: 'Jewelry',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: '5',
    name: 'Midnight Silk Slip Dress',
    price: 75.00,
    description: 'Luxurious silk slip dress that transitions perfectly from day to night.',
    category: 'Dresses',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: '6',
    name: 'Cyberpunk Shield Shades',
    price: 24.99,
    originalPrice: 49.99,
    discountPercentage: 50,
    description: 'Futuristic oversized sunglasses with iridescent purple lenses and UV400 protection.',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1511499767390-903390e6fbc4?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: '7',
    name: 'Violet Quilted Handbag',
    price: 110.00,
    description: 'Elegant quilted leather handbag with gold chain strap and multiple compartments.',
    category: 'Bags',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: '8',
    name: 'Cropped Lilac Puffer',
    price: 68.00,
    originalPrice: 120.00,
    discountPercentage: 43,
    description: 'Water-resistant cropped puffer jacket in high-gloss lilac finish.',
    category: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
];
